/*
 * File: app/controller/AssetTracker.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AssetTracker.controller.AssetTracker', {
    extend: 'Ext.app.Controller',

    requires: [
        'Ext.MessageBox'
    ],

    config: {
        refs: {
            assetForm: 'assetform',
            topTabBar: 'tabbar'
        },

        control: {
            "button#saveBtn": {
                tap: 'onSaveBtnTap'
            },
            "button#newBtn": {
                tap: 'onNewBtnTap'
            },
            "list#assetList": {
                itemtap: 'onAssetListItemTap'
            },
            "button#deleteBtn": {
                tap: 'onDeleteBtnTap'
            }
        }
    },

    onSaveBtnTap: function(button, e, eOpts) {
        var me = this;

        var fp = me.getAssetForm();

        var mod = fp.getRecord();

        if (mod) {
            fp.updateRecord(mod);
        } else {
            mod = Ext.create('AssetTracker.model.Asset');
            fp.updateRecord(mod);
            Ext.getStore('Assets').add(mod);
        }

        Ext.Msg.alert('Success', 'Your info was saved successfully', function(){
            me.clearAssetForm();
        });
    },

    onNewBtnTap: function(button, e, eOpts) {
        this.clearAssetForm();
    },

    onAssetListItemTap: function(dataview, index, target, record, e, eOpts) {
        this.getAssetForm().setRecord(record);
        this.getTopTabBar().setActiveTab(0);
    },

    onDeleteBtnTap: function(button, e, eOpts) {
        var fp = this.getAssetForm();
        var mod = fp.getRecord();

        if (mod)
        {
            var as = Ext.getStore('Assets');
            as.remove(mod);
            this.getTopTabBar().setActiveTab(1);
            this.clearAssetForm();
        }
    },

    clearAssetForm: function() {
        var fp = this.getAssetForm();

        fp.setValues({
            name: '',
            serial: '',
            deviceType: 1,
            dept: 1
        });

        fp.setRecord(null);
    }

});