/*
 * File: app/store/Depts.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AssetTracker.store.Depts', {
    extend: 'Ext.data.Store',

    requires: [
        'AssetTracker.model.Dept'
    ],

    config: {
        data: [
            {
                id: 1,
                name: 'Engineering'
            },
            {
                id: 2,
                name: 'Finance'
            },
            {
                id: 3,
                name: 'HR'
            },
            {
                id: 4,
                name: 'Sales'
            },
            {
                id: 5,
                name: 'Marketing'
            }
        ],
        model: 'AssetTracker.model.Dept',
        storeId: 'Depts'
    }
});