/*
 * File: app/view/AssetForm.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AssetTracker.view.AssetForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.assetform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Select',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer'
    ],

    config: {
        layout: 'fit',
        items: [
            {
                xtype: 'fieldset',
                title: 'Asset',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Name',
                        name: 'name'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Serial',
                        name: 'serial'
                    },
                    {
                        xtype: 'selectfield',
                        label: 'Device',
                        name: 'deviceType',
                        displayField: 'name',
                        store: 'DeviceTypes',
                        valueField: 'id'
                    },
                    {
                        xtype: 'selectfield',
                        label: 'Dept',
                        name: 'dept',
                        displayField: 'name',
                        store: 'Depts',
                        valueField: 'id'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'newBtn',
                        text: 'New'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'deleteBtn',
                        text: 'Delete'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        itemId: 'saveBtn',
                        text: 'Save'
                    }
                ]
            }
        ]
    }

});