/*
 * File: app/view/Mainview.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AssetTracker.view.Mainview', {
    extend: 'Ext.Container',
    alias: 'widget.Mainview',

    requires: [
        'AssetTracker.view.AssetForm',
        'AssetTracker.view.AssetList',
        'Ext.TitleBar',
        'Ext.tab.Panel',
        'Ext.form.Panel',
        'Ext.dataview.List',
        'Ext.tab.Bar'
    ],

    config: {
        layout: 'fit',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Asset Tracker'
            },
            {
                xtype: 'tabpanel',
                items: [
                    {
                        xtype: 'container',
                        title: 'Entry',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'assetform',
                                id: 'assetform'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'List',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'assetList'
                            }
                        ]
                    }
                ],
                tabBar: {
                    docked: 'top',
                    layout: {
                        type: 'hbox',
                        pack: 'center'
                    }
                }
            }
        ]
    }

});